from dataclasses import dataclass, field
from typing import List, Optional


def sanitize_for_logging(text):
    """Sanitize text for logging by removing problematic characters."""
    if not text:
        return ""
    
    # Handle non-string inputs
    if not isinstance(text, str):
        try:
            text = str(text)
        except:
            return "[Non-string content]"
    
    try:
        # Use a more aggressive approach: keep only ASCII characters
        # This will remove all non-ASCII characters instead of replacing them
        return ''.join(c for c in text if ord(c) < 128)
    except:
        # If that fails for any reason, return a safe string
        return "[Content with unsupported characters]"
    

@dataclass
class SummaryItem:
    """
    Standardized summary model for all content types.
    This ensures consistent structure for summaries across different platforms.
    
    Attributes:
        type (str): Source platform type (youtube, twitter, article, etc.)
        title (str): Content title
        author (str): Main author/creator
        url (str): Original content URL
        summary (str): Generated summary text
        tags (List[str]): Tags/keywords generated by the LLM
        thread_url (str): URL to the Discord thread (populated later)
    """
    type: str  # Source platform type (youtube, twitter, article, etc.)
    title: str  # Content title
    author: str  # Main author/creator
    url: str  # Original content URL
    summary: str  # Generated summary text
    tags: List[str] = field(default_factory=list)  # Tags/keywords generated by the LLM
    thread_url: str = ""  # URL to the Discord thread (populated later)

