version: "3.8"

services:
  pia-discord-bot:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./pia-discord-bot_config.json:/app/pia-discord-bot_config.json
